### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by yashodhank** [frappe/erpnext_shopify_broker#9]
![image](https://cloud.githubusercontent.com/assets/1083792/22174774/fc598b9a-e00b-11e6-895c-30d393f240d0.png)

![image](https://cloud.githubusercontent.com/assets/1083792/22174768/df644228-e00b-11e6-8ac0-80c948c36c3e.png)

**Comment by saurabh6790** [comment]
Fixed!! Thanks for reporting.
